services:

  network:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vse-network
    command: ["/app/vse-network"]
    ports:
      - "9001:9001"

  billing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vse-billing
    command: ["/app/vse-billing"]
    ports:
      - "9002:9002"

  control:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vse-control
    command: ["/app/vse-control"]
    ports:
      - "9000:9000"
    environment:
      CONTROL_PORT: 9000
      NETWORK_HOST: network
      NETWORK_PORT: 9001
      BILLING_HOST: billing
      BILLING_PORT: 9002
    depends_on:
      - network
      - billing
